--
-- PostgreSQL database dump
--

-- Dumped from database version 15.3
-- Dumped by pg_dump version 15.3

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: courses; Type: SCHEMA; Schema: -; Owner: demo
--

CREATE SCHEMA courses;


ALTER SCHEMA courses OWNER TO demo;

--
-- Name: public; Type: SCHEMA; Schema: -; Owner: demo
--

-- *not* creating schema, since initdb creates it


ALTER SCHEMA public OWNER TO demo;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: course; Type: TABLE; Schema: courses; Owner: demo
--

CREATE TABLE courses.course (
    id bigint NOT NULL,
    author text,
    name character varying(200) NOT NULL
);


ALTER TABLE courses.course OWNER TO demo;

--
-- Name: course_id_seq; Type: SEQUENCE; Schema: courses; Owner: demo
--

ALTER TABLE courses.course ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME courses.course_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    MAXVALUE 2147483647
    CACHE 1
);


--
-- Name: databasechangelog; Type: TABLE; Schema: courses; Owner: demo
--

CREATE TABLE courses.databasechangelog (
    id character varying(255) NOT NULL,
    author character varying(255) NOT NULL,
    filename character varying(255) NOT NULL,
    dateexecuted timestamp without time zone NOT NULL,
    orderexecuted integer NOT NULL,
    exectype character varying(10) NOT NULL,
    md5sum character varying(35),
    description character varying(255),
    comments character varying(255),
    tag character varying(255),
    liquibase character varying(20),
    contexts character varying(255),
    labels character varying(255),
    deployment_id character varying(10)
);


ALTER TABLE courses.databasechangelog OWNER TO demo;

--
-- Name: databasechangeloglock; Type: TABLE; Schema: courses; Owner: demo
--

CREATE TABLE courses.databasechangeloglock (
    id integer NOT NULL,
    locked boolean NOT NULL,
    lockgranted timestamp without time zone,
    lockedby character varying(255)
);


ALTER TABLE courses.databasechangeloglock OWNER TO demo;

--
-- Name: roles; Type: TABLE; Schema: courses; Owner: demo
--

CREATE TABLE courses.roles (
    id bigint NOT NULL,
    name character varying(100) NOT NULL,
    created timestamp without time zone DEFAULT now() NOT NULL,
    updated timestamp without time zone DEFAULT now() NOT NULL,
    status character varying(25) DEFAULT 'ACTIVE'::character varying NOT NULL
);


ALTER TABLE courses.roles OWNER TO demo;

--
-- Name: roles_id_seq; Type: SEQUENCE; Schema: courses; Owner: demo
--

ALTER TABLE courses.roles ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME courses.roles_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: user_roles; Type: TABLE; Schema: courses; Owner: demo
--

CREATE TABLE courses.user_roles (
    user_id bigint,
    role_id bigint
);


ALTER TABLE courses.user_roles OWNER TO demo;

--
-- Name: users; Type: TABLE; Schema: courses; Owner: demo
--

CREATE TABLE courses.users (
    id bigint NOT NULL,
    username character varying(100) NOT NULL,
    email character varying(255) NOT NULL,
    first_name character varying(100) NOT NULL,
    last_name character varying(100) NOT NULL,
    password character varying(255) NOT NULL,
    created timestamp without time zone DEFAULT now() NOT NULL,
    updated timestamp without time zone DEFAULT now() NOT NULL,
    status character varying(25) DEFAULT 'ACTIVE'::character varying NOT NULL
);


ALTER TABLE courses.users OWNER TO demo;

--
-- Name: users_id_seq; Type: SEQUENCE; Schema: courses; Owner: demo
--

ALTER TABLE courses.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME courses.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: course; Type: TABLE DATA; Schema: courses; Owner: demo
--

COPY courses.course (id, author, name) FROM stdin;
1	Петров А.В	1 Основы кройки и шитья
2	Мошкина А.В	2 Введение в архитектуру дизайна
3	Смирнов А.А	Основы ООП
14	Иванов А.А	Линейная алгебра
15	Иванов А.Ю	Линейная алгебра 2 курс
17	Сергеев А.Ю	Основы алгоритмизации
18	Сергеев А.Ю	Основы алгоритмизаци 2 курс
19	Сергеева А.Ю	Основы алгоритмизации 3 курс
20	Сергеева А.Е	Основы алгоритмизации 4 курс
25	Сергеева А.Н	Основы алгоритмизации 5 курс
26	Сергеева А.E	Основы алгоритмизации 5 курс
27	Сергеева А.E	Основы алгоритмизации 6 курс
28	Сергеева А.E	Основы алгоритмизации 7 курс
32	Сергеева А.E	Основы алгоритмизации 8 курс
\.


--
-- Data for Name: roles; Type: TABLE DATA; Schema: courses; Owner: demo
--

COPY courses.roles (id, name, created, updated, status) FROM stdin;
1	ROLE_USER	2023-07-09 18:07:38.006607	2023-07-09 18:07:38.006607	ACTIVE
2	ROLE_ADMIN	2023-07-09 18:07:38.006607	2023-07-09 18:07:38.006607	ACTIVE
3	ROLE_MODERATOR	2023-07-11 11:16:03.448061	2023-07-11 11:16:03.448061	ACTIVE
\.


--
-- Data for Name: user_roles; Type: TABLE DATA; Schema: courses; Owner: demo
--

COPY courses.user_roles (user_id, role_id) FROM stdin;
1	1
1	2
8	1
10	1
\.


--
-- Data for Name: users; Type: TABLE DATA; Schema: courses; Owner: demo
--

COPY courses.users (id, username, email, first_name, last_name, password, created, updated, status) FROM stdin;
8	test111@test111.test111	test111@test111.test111	test111	test111	$2a$10$9vGeW8xowVVLFkeb68Gs6OmX38fL3pVgv5C5FIzqysSUZiyV.p8bK	2023-07-11 15:44:59.417	2023-07-11 15:44:59.417	NOT_ACTIVE
1	test	test@test.test	test	test	$2a$04$oWv/60MC7yAY6mE.45SB/e6QqxqpL55JmFW33Ntn10zd3UViYdbM2	2023-07-10 13:12:05	2023-07-10 13:12:09	ACTIVE
10	test222@test222.test222	test222@test222.test222	test222	test222	$2a$10$K82RDIjiPVQEgVcEp2cSNOhkHSHEviyrkjc7GCl5FvavkprMiCj96	2023-07-11 16:15:01.944	2023-07-11 16:15:01.944	NOT_ACTIVE
\.


--
-- Name: course_id_seq; Type: SEQUENCE SET; Schema: courses; Owner: demo
--

SELECT pg_catalog.setval('courses.course_id_seq', 32, true);


--
-- Name: roles_id_seq; Type: SEQUENCE SET; Schema: courses; Owner: demo
--

SELECT pg_catalog.setval('courses.roles_id_seq', 3, true);


--
-- Name: users_id_seq; Type: SEQUENCE SET; Schema: courses; Owner: demo
--

SELECT pg_catalog.setval('courses.users_id_seq', 10, true);


--
-- Name: course course_pkey; Type: CONSTRAINT; Schema: courses; Owner: demo
--

ALTER TABLE ONLY courses.course
    ADD CONSTRAINT course_pkey PRIMARY KEY (id);


--
-- Name: databasechangeloglock databasechangeloglock_pkey; Type: CONSTRAINT; Schema: courses; Owner: demo
--

ALTER TABLE ONLY courses.databasechangeloglock
    ADD CONSTRAINT databasechangeloglock_pkey PRIMARY KEY (id);


--
-- Name: roles roles_name_key; Type: CONSTRAINT; Schema: courses; Owner: demo
--

ALTER TABLE ONLY courses.roles
    ADD CONSTRAINT roles_name_key UNIQUE (name);


--
-- Name: roles roles_pkey; Type: CONSTRAINT; Schema: courses; Owner: demo
--

ALTER TABLE ONLY courses.roles
    ADD CONSTRAINT roles_pkey PRIMARY KEY (id);


--
-- Name: users users_email_key; Type: CONSTRAINT; Schema: courses; Owner: demo
--

ALTER TABLE ONLY courses.users
    ADD CONSTRAINT users_email_key UNIQUE (email);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: courses; Owner: demo
--

ALTER TABLE ONLY courses.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: users users_username_key; Type: CONSTRAINT; Schema: courses; Owner: demo
--

ALTER TABLE ONLY courses.users
    ADD CONSTRAINT users_username_key UNIQUE (username);


--
-- Name: user_roles fk_user_roles_roles; Type: FK CONSTRAINT; Schema: courses; Owner: demo
--

ALTER TABLE ONLY courses.user_roles
    ADD CONSTRAINT fk_user_roles_roles FOREIGN KEY (role_id) REFERENCES courses.roles(id) ON UPDATE RESTRICT ON DELETE CASCADE;


--
-- Name: user_roles fk_user_roles_user; Type: FK CONSTRAINT; Schema: courses; Owner: demo
--

ALTER TABLE ONLY courses.user_roles
    ADD CONSTRAINT fk_user_roles_user FOREIGN KEY (user_id) REFERENCES courses.users(id) ON UPDATE RESTRICT ON DELETE CASCADE;


--
-- PostgreSQL database dump complete
--

